spring:
    application:
        name: Altair
    jpa:
        hibernate:
            ddl-auto: create
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/testdb
        username: test
        password: test
    thymeleaf:
        cache: false
    mvc:
        log-request-details: true
        async:
            request-timeout: 60000
logging:
    level:
        org:
            springframework: INFO
altair:
    security:
        max-attempts: 3                         # Maximum number of failed login attempts before the account is locked
        lockout-time: 300                       # Time in seconds that the account is locked after too many failed login attempts
        default-password: hikoboshi             # Default password for the admin, please change this after deployment
    observatory:
        status-update-interval: 2000            # Interval in ms between status updates for the observatory. If set too fast, it might hang the server/devices.
        synchronous-timeout: 60000              # Timeout in ms for synchronous operations. If set too high, failed operations might never finish, and if set too low, some successful operations might get interrupted. Set to 0 to disable timeouts (not recommended).
        camera:
            max-cooldown-rate: 2.5              # Maximum cooldown rate for the camera, in °C/min, if hardware does not support auto ramping.
            min-cooldown-rate: 0.5              # Minimum cooldown rate for the camera, in °C/min, if hardware does not support auto ramping. If it cools down too slowly, the cooler will stop cooling it further.
            max-warmup-rate: 1.5                # Maximum warmup rate for the camera, in °C/min, if hardware does not support auto ramping.
            cooler-saturation-threshold: 95.0   # If the cooler reaches this power level, it is considered saturated
            image-buffer-size: 268435456        # Size of the image processing buffer, in bytes. Use '-1' to disable the limiter and use the maximum available memory.
    astrometrics:
        site-latitude: 37.2597                  # Latitude of the observatory, in decimal degrees, north is positive
        site-longitude: -6.9325                 # Longitude of the observatory, in decimal degrees, east is positive
        site-elevation: 130.0                   # Elevation of the observatory, in meters
        horizon-line: 3.0                       # Horizon line, in degrees, above which the telescope can see




