spring:
    application:
        name: Altair
    jpa:
        hibernate:
            ddl-auto: create
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/testdb
        username: test
        password: test
    thymeleaf:
        cache: false
    mvc:
        log-request-details: true
logging:
    level:
        org:
            springframework: INFO
altair:
    security:
        max-attempts: 3
        lockout-time: 300
        default-password: hikoboshi
    observatory:
        status-update-interval: 500


